#!/bin/bash

# Load settings
. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/settings

printf "\
m_bndId
m_bndryId
m_delete
m_flowCellId
m_globalId
m_haloLayer
m_hasBeenRefined
m_inShadowLayer
m_isBndryCell
m_isBndryGhostCell
m_isGHaloCell
m_isGWindowCell
m_isInterface
m_isInterfaceChild
m_isInterfaceParent
m_kappa
m_level
m_noChildIds
m_noOffsprings
m_noRcnstrctnNghbrIds
m_nu
m_onlyBoundary
m_parentId
m_periodicDirection
m_quasiPeriodicDirection
m_regridTrigger
m_spongeBndryId1
m_spongeBndryId2
m_spongeBndryId3
m_spongeFactor
m_spongeFactorStart
m_vortexCriterion
m_weight
m_workLoad
b_properties
m_bandNghbrIds
m_bodyId
m_childIds
m_coordinates
m_curvature
m_distributions
m_distributionsThermal
m_dt1Variables
m_dt2Variables
m_fExt
m_flameSpeed
m_fluctuations
m_inBand
m_inGamma
m_isGBndryCell
m_levelSetFunction
m_multilevelVars
m_nghbrIds
m_noNghbrIds
m_normalExtensionVelocity
m_normalVector
m_oldDistributions
m_oldDistributionsThermal
m_oldVariables
m_rcnstrctnNghbrIds
m_reactionRate
m_restrictedRHS
m_slope
m_stretch
m_tau
m_variables
m_vorticity
" | xargs $REGEX_AUX_DIR/add_underscore.sh
