# Include guard
if(__get_compiler)
  return()
endif()
set(__get_compiler YES)

# Determine the name of the current C++ compiler and save it to _var
function(get_compiler _var)
  if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    set(${_var} "GNU" PARENT_SCOPE)
  elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    set(${_var} "Clang" PARENT_SCOPE)
  elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Intel")
    set(${_var} "Intel" PARENT_SCOPE)
  elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "NVHPC")
    set(${_var} "NVHPC" PARENT_SCOPE)
  elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "PGI")
    set(${_var} "PGI" PARENT_SCOPE)
  elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "XL")
    set(${_var} "IBM" PARENT_SCOPE)
  elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Cray")
    set(${_var} "Cray" PARENT_SCOPE)
  elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Fujitsu")
    set(${_var} "Fujitsu" PARENT_SCOPE)
  else()
    set(${_var} ${CMAKE_CXX_COMPILER_ID})
  endif()
endfunction()
