# Include guard
if (__get_host)
  return()
endif ()
set(__get_host YES)

# Determine the current host and return it in _var
function(get_host _var)
  if("$ENV{MAIA_HOST_FILE}" STREQUAL "")
    site_name(_raw_host)
    if (${_raw_host} MATCHES "aia[0-9]*")
      set(${_var} "AIA" PARENT_SCOPE)
    elseif (${_raw_host} MATCHES "juwels*")
      set(${_var} "Juwels" PARENT_SCOPE)
    elseif (${_raw_host} MATCHES "hawk-login*")
      set(${_var} "Hawk" PARENT_SCOPE)
    elseif (${_raw_host} MATCHES "daint*")
      set(${_var} "PizDaint" PARENT_SCOPE)      
    elseif (${_raw_host} MATCHES "hpc.itc.rwth-aachen.de")
      set(${_var} "CLAIX" PARENT_SCOPE)
    elseif (${_raw_host} MATCHES "ivb[0-9]*")
      set(${_var} "PSG" PARENT_SCOPE)
    elseif (${_raw_host} MATCHES "jupp[1-4]0")
      set(${_var} "Power8" PARENT_SCOPE)
    elseif (${_raw_host} MATCHES "jrl[0-9][0-9]")
      set(${_var} "Jureca" PARENT_SCOPE)
    elseif (${_raw_host} MATCHES "fe[0-9][0-9]p[0-9][0-9]")
      set(${_var} "Klogin" PARENT_SCOPE)
    elseif (${_raw_host} MATCHES "pps[0-9]")
      set(${_var} "Klogin" PARENT_SCOPE)
    else ()
      set(${_var} ${_raw_host} PARENT_SCOPE)
    endif ()
    unset(_raw_host CACHE)
  else()
    set(${_var} "CUSTOM_HOST_FILE" PARENT_SCOPE)
  endif()
endfunction()
